name: flutter_fcm
description: An app to test the ways of firebase cloud messaging

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  cloud_firestore: ^4.9.3
  flutter_local_notifications: ^16.1.0
  http: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
